# Generated by Django 3.2 on 2022-06-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproperty', '0002_auto_20220608_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='requisition_time',
            field=models.TextField(blank=True, default='', null=True, verbose_name='领用日期'),
        ),
    ]
