# Generated by Django 3.2 on 2022-06-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproperty', '0003_alter_info_requisition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='requisition_time',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='领用日期'),
        ),
    ]
