# Generated by Django 3.2 on 2022-06-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproperty', '0004_alter_info_requisition_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='asset_code',
            field=models.CharField(max_length=32, verbose_name='资产编码'),
        ),
        migrations.AlterField(
            model_name='info',
            name='num',
            field=models.IntegerField(verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='info',
            name='pro_name',
            field=models.CharField(max_length=32, verbose_name='资产名称'),
        ),
    ]
