# Generated by Django 3.2 on 2022-07-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproperty', '0005_auto_20220613_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_code', models.CharField(max_length=32, verbose_name='资产编码')),
                ('alters_data', models.DateTimeField(blank=True, default='', null=True, verbose_name='时间')),
                ('signature', models.ImageField(blank=True, max_length=1000, null=True, upload_to='signature/', verbose_name='签名')),
                ('device', models.CharField(blank=True, max_length=32, null=True, verbose_name='设备名')),
                ('specification', models.CharField(blank=True, max_length=32, null=True, verbose_name='规格型号')),
                ('user_name', models.CharField(blank=True, max_length=8, null=True, verbose_name='使用人')),
                ('department', models.CharField(blank=True, max_length=8, null=True, verbose_name='部门')),
            ],
            options={
                'db_table': 'Grant',
            },
        ),
    ]
