# Generated by Django 3.2 on 2022-07-12 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproperty', '0007_auto_20220711_1012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='asset_code',
        ),
        migrations.RemoveField(
            model_name='grant',
            name='department',
        ),
        migrations.AddField(
            model_name='grant',
            name='info_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myproperty.info', verbose_name='资产码'),
        ),
    ]
