# Generated by Django 3.2 on 2022-07-12 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myproperty', '0008_auto_20220712_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myproperty.info'),
        ),
        migrations.AddField(
            model_name='grant',
            name='sn_num',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='sn'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='info_code',
            field=models.CharField(max_length=32, verbose_name='资产编码'),
        ),
    ]
