# Generated by Django 3.2 on 2022-07-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproperty', '0009_auto_20220712_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grant',
            name='alters_data',
        ),
        migrations.AddField(
            model_name='grant',
            name='alters_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='时间'),
        ),
    ]
