# Generated by Django 3.2 on 2022-08-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myproperty', '0013_alter_grant_signature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'verbose_name': '签名', 'verbose_name_plural': '签名'},
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'verbose_name': '资产表', 'verbose_name_plural': '资产表'},
        ),
    ]
