# Generated by Django 3.2 on 2022-08-16 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myproperty', '0014_auto_20220812_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='add_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='requisition_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='领用日期'),
        ),
    ]
