# Generated by Django 3.2 on 2022-08-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myproperty', '0015_auto_20220816_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='add_time',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='info',
            name='requisition_time',
            field=models.DateTimeField(blank=True, default='', null=True, verbose_name='领用日期'),
        ),
    ]
